# This is a basic workflow to help you get started with Actions

name: create-snapshot

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1 
      with:
          java-version: '11'
          architecture: 'x64'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dist  
    - name: Create Distribution   
      run: distribution/create-distribution-linux.sh SNAPSHOT-$(date +"%Y-%m-%d_%H-%M-%S")   
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './distribution/freerouting-SNAPSHOT-*-executable.jar;./distribution/freerouting-SNAPSHOT-*-linux-x64.zip'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}      
   
  build-windows:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1 
      with:
          java-version: '11'
          architecture: 'x64'
    - name: Build with Gradle
      run: .\gradlew.bat dist 
    - name: Create Distribution   
      run: distribution\create-distribution-SNAPSHOT-windows.bat "SNAPSHOT-$(([datetime]::now).tostring("yyyy-MM-dd_HH-mm-ss"))"   
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './distribution/freerouting-SNAPSHOT-*-windows-x64.msi'
          release-tag: SNAPSHOT 
          repo-token: ${{ secrets.GITHUB_TOKEN }}   
          
  build-windows-x86:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1 
      with:
          java-version: '11'
          architecture: x86
    - name: Build with Gradle
      run: .\gradlew.bat dist 
    - name: Create Distribution   
      run: distribution\create-distribution-SNAPSHOT-windows-x86.bat "SNAPSHOT-$(([datetime]::now).tostring("yyyy-MM-dd_HH-mm-ss"))"   
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './distribution/freerouting-SNAPSHOT-*-windows-x86.msi'
          release-tag: SNAPSHOT 
          repo-token: ${{ secrets.GITHUB_TOKEN }}   

  build-macos:

    runs-on: [macos]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1 
      with:
          java-version: '11'
          architecture: 'x64'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew dist  
    - name: Create Distribution   
      run: distribution/create-distribution-macos.sh SNAPSHOT-$(date +"%Y-%m-%d_%H-%M-%S")
    - uses: AButler/upload-release-assets@v2.0
      with:
          files: './distribution/freerouting-SNAPSHOT-*-macos-x64.dmg'
          release-tag: SNAPSHOT
          repo-token: ${{ secrets.GITHUB_TOKEN }}        
